name: "tfupdate"

on:
  workflow_dispatch: null
jobs:
  update_terraform_versions:
    timeout-minutes: 30
    name: Update terraform versions
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: tfupdate
        uses: daisaru11/tfupdate-github-actions@v1
        with:
          tfupdate_subcommand: terraform
          tfupdate_path: "."
